config/routes.rb
MobileWrx::Application.routes.draw do

  devise_for :users

  resources :users, only: [:show]

  resources :promotions

  match "promotions" => "welcome#promotions", via: :get

  match "how" => "welcome#how", via: :get

  match "faq" => "welcome#faq", via: :get

  match "about" => "welcome#about", via: :get

  match "contact" => "welcome#contact", via: :get

  root :to => 'welcome#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user

    # if a member, they can manage their own posts
    # (or create new ones)
    if user.role? :member
      can :manage, Promotion, :user_id => user.id
    end

    # Moderators can delete any post
    if user.role? :moderator
      can :destroy, Promotion
    end

    # Admins can do anything
    if user.role? :admin
      can :manage, :all
    end

    can :read, :all
  end
end

app/models/promotion.rb
class Promotion < ActiveRecord::Base
  attr_accessible :description, :expiration, :price, :qrcode, :title, :website, :image

  belongs_to :user

  mount_uploader :image, ImageUploader
  mount_uploader :qrcode, QrcodeUploader

  default_scope order('created_at DESC')

  validates :title, length: { maximum: 20 }, presence: true
  validates :description, length: { maximum: 25 }, presence: true
  validates :price, presence: true
  validates :expiration, presence: true
  validates :website, presence: true
  validates :image, presence: true
  validates :qrcode, presence: true

  scope :visible_to, lambda { |user| user ? scoped : joins(:promotion).where('promotions.public' => true) }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :avatar
  # attr_accessible :title, :body

  has_many :promotions
  before_create :set_member
  mount_uploader :avatar, AvatarUploader

  ROLES = %w[member moderator admin]
def role?(base_role)
  role.nil? ? false : ROLES.index(base_role.to_s) <= ROLES.index(role)
end

private

  def set_member
    self.role = 'member'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end

  def after_sign_in_path_for(resource)
    user_path(resource)
  end
end

app/controllers/promotions_controller.rb
class PromotionsController < ApplicationController
  def index
  	@promotions = Promotion.paginate(page: params[:page], per_page: 4)
  end

  def show
  	@promotion = Promotion.find(params[:id])
  end

  def new
  	@promotion = Promotion.new
    # authorize! :create, Promotion, message: "You need to be a memeber to create a new promotion."
  end

  def create
  @promotion = current_user.promotions.build(params[:promotion])
  # authorize! :create, @promotion, message: "You need to be signed up to do that."
  if @promotion.save
    flash[:notice] = "Promotion was saved."
    redirect_to @promotion
  else
    flash[:error] = "There was an error saving the promotion. Please try again."
    render :new
  end
end

  def edit
    @promotion = Promotion.find(params[:id])
    # authorize! :edit, @promotion, message: "You need to own the promotion to edit it."
  end

  def update
    @promotion = Promotion.find(params[:id])
    # authorize! :update, @promotion, message: "You need to own the promotion to edit it."
    if @promotion.update_attributes(params[:promotion])
      flash[:notice] = "Promotion was updated."
      redirect_to @promotion
    else
      flash[:error] = "There was an error saving the promotion. Please try again."
      render :edit
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @promotions = @user.promotions.visible_to(current_user)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def promotions
  end

  def how
  end

  def faq
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def will_paginate(collection_or_options = nil, options = {})
    if collection_or_options.is_a? Hash
      options, collection_or_options = collection_or_options, nil
    end
    unless options[:renderer]
      options = options.merge :renderer => BootstrapLinkRenderer
    end
    super *[collection_or_options, options].compact
  end

end

app/helpers/promotions_helper.rb
module PromotionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MobileWrx</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<ul class="nav nav-tabs">
		<li><%= link_to "Home", root_path %></li>
		<li><%= link_to "Promotions", promotions_path %></li>
		<li><%= link_to "How it WRX", how_path %></li>
		<li><%= link_to "FAQ", faq_path %></li>
		<li><%= link_to "About Us", about_path %></li>
		<li><%= link_to "Contact Us", contact_path %></li>

		<div class="pull-right user-info">
          <% if current_user %>
            <%= image_tag(current_user.avatar.tiny.url, class: "img-rounded") if current_user.avatar? %>
        	   Hello <%= link_to (current_user.name || current_user.email), current_user %>!
            <%= link_to edit_user_registration_path, class: 'btn btn-mini' do %>
              <i class="icon-user"> </i>
            <% end %>
            <%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-mini' do %>
              <i class="icon-share-alt"> </i>
            <% end %>
            <% else %>
              <%= link_to "Sign In", new_user_session_path %> or
              <%= link_to "Sign Up", new_user_registration_path %>
           <% end %>
         </div>
	</ul>

	<% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:error] %>
        <div class="alert alert-error">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:error] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>

<%= yield %>
</div>

</body>
</html>

app/views/promotions/_promotion.html.erb
<div class="media">
  <%= link_to [promotion], class: 'pull-left' do %>
  <% end %>
  <div class="media-body">
    <h4 class="media-heading">
    </h4>
    <small>
      <%= promotion.title %>
      submitted <%= time_ago_in_words(promotion.created_at) %> ago by
      <%= link_to promotion.user.name, promotion.user %><br/>
    </small>
  </div>
</div>

app/views/promotions/edit.html.erb
<center>
<div class="row">
	<div class="span3">
	</div>
		<div class="span5">
    	<br>
  		<h1><%= image_tag("mobilewrxlogo.jpg") %></h1>
		</div>
	</div>
  <br>
  <div class="row">
  <div class="span2">
  </div>
  	<div class="span7">
  <h5>Please make the necessary changes to your promotion:</h5>
</div>
</div>
<br>
<br>
<div class="row">
	<div class="span4">
	</div>
		<div class="span3">
<%= simple_form_for @promotion do |f| %>
	<p><%= f.input :title, label: false, placeholder: 'Title' %></p>
	<p><%= f.input :description, :input_html => { :rows => 2}, label: false, placeholder: 'Enter Brief description: no more than 30 characters' %></p>
	<p><%= f.input :price, label: false, placeholder: 'Price' %></p>
	<p><%= f.input :expiration, label: false, placeholder: 'Expiry Date' %></p>
	<p><%= f.input :website, label: false, placeholder: 'Website' %></p>
	<p><%= f.file_field :image %><font color="blue">*Upload Image</font></p>
	<p><%= f.file_field :qrcode %><font color="blue">*Upload QR code</font></p>
	<br>
	<p><%= f.submit %></p>
	<% end %>
</div>
</div>
</div>

app/views/promotions/index.html.erb
<div>
<center>
    <br>
  <h1><%= image_tag("mobilewrxlogo.jpg") %></h1>
   <h5>Latest promotions!</h5>
<br>
</center>
<br>
<% @promotions.each do |promotion| %>
<div class="row">
	<div class="span3">
		<div class="thumbnail">
			<p><%= image_tag(promotion.image_url, class: "img-rounded") %></p>
			<p align="center"><%= promotion.title %></p>
			<p align="center"><%= promotion.description %></p>
			<p align="center"><%= promotion.price %></p>
			<p align="center"><%= promotion.expiration %></p>
			<p align="center"><%= link_to promotion.website %></p>
			<p align="center"><%= image_tag(promotion.qrcode_url, class: "img-rounded") %></p>
			<p align="center"><a href="#" class="btn btn-mini btn-primary">More</a></p>
		</div>
		</div>


<% end %>
</div>

<div class="row">
	<div class="span12">
		<div align="center">
			<p><%= will_paginate @promotions %></p>
		</div>
	</div>
</div>

app/views/promotions/new.html.erb
<center>
<div class="row">
	<div class="span3">
	</div>
		<div class="span5">
    	<br>
  		<h1><%= image_tag("mobilewrxlogo.jpg") %></h1>
		</div>
	</div>
  <br>
  <div class="row">
  <div class="span2">
  </div>
  	<div class="span7">
  <h5>Please fill out the form below describing your promotion.</h5>
</div>
</div>
<br>
<br>
<div class="row">
	<div class="span4">
	</div>
		<div class="span3">
<%= simple_form_for @promotion do |f| %>
	<p><%= f.input :title, label: false, placeholder: 'Title' %></p>
	<p><%= f.input :description, :input_html => { :rows => 2}, label: false, placeholder: 'Enter Brief description: no more than 30 characters' %></p>
	<p><%= f.input :price, label: false, placeholder: 'Price' %></p>
	<p><%= f.input :expiration, label: false, placeholder: 'Expiry Date' %></p>
	<p><%= f.input :website, label: false, placeholder: 'Website' %></p>
	<p><%= f.file_field :image %><font color="blue">*Upload Image</font></p>
	<p><%= f.file_field :qrcode %><font color="blue">*Upload QR code</font></p>
	<br>
	<p><%= f.submit %></p>
	<% end %>
</div>
</div>
</div>

app/views/promotions/show.html.erb
<center>
<div class="row">
  <div class="span3">
  </div>
    <div class="span5">
      <br>
      <h1><%= image_tag("mobilewrxlogo.jpg") %></h1>
    </div>
  </div>
  <br>
  <div class="row">
  <div class="span2">
  </div>
    <div class="span7">
  <h5>Please confirm or edit your promotion:</h5>
</div>
</div>
<br>
<br>
<div class="row">
  <div class="span4">
  </div>
  <div class="span3">
    <div class="thumbnail">
       <p><%= image_tag(@promotion.image_url, class: "image-rounded") if @promotion.image? %></p>
      <div class="caption">
        <p><%= @promotion.title %></h3>
        <p align="center"><%= @promotion.description %><pp>
        <p align="center"><%= @promotion.price %></p>
        <p align><%= @promotion.expiration %></p>
        <p align><%= @promotion.website %></p>
        <p align="center"><%= image_tag(@promotion.qrcode_url, class: "image-rounded") if @promotion.qrcode? %></p>
        <p align="center"><a href="#" class="btn btn-primary">Buy</a></p>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="span4">
  </div>
  <div class="span3">
    <br>
<%= link_to "Edit", edit_promotion_path(@promotion), class: 'btn btn-primary' %>
<%= link_to "Confirm", promotions_path, class: 'btn btn-primary' %>
</div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="span12">
    <div class="media">
      <% if @user.avatar? %>
        <%= image_tag @user.avatar.url, class: 'pull-left', class: "img-rounded" %>
      <% end %>
      <div class="media-body">
        <h2 class="media-heading"><%= @user.name %></h2>
        <small>
          <%= pluralize(@user.promotions.count, 'promotions') %>
        </small>
      </div>
    </div>
    <% if can? :create, Promotion %>
    <%= link_to "New Promotion", new_promotion_path, class: 'btm btn-primary' %>
  <% end %>
  </div>
</div>
<br>

<div class="row">
  <div class="tabbable">
    <ul class="nav nav-tabs">
      <li class="active"><a href="#promotions" data-toggle="tab">Promotions</a></li>
      <li><a href="#" data-toggle="tab">Profile</a></li>
    </ul>
    <div class="tab-content">
      <div class="tab-pane active" id="promotions">
        <h3>Here is a list of your promotions.</h3>
        <%= render @promotions %>
      </div>
    </div>
  </div>
</div>

app/views/welcome/about.html.erb
<div>
  <center>
    <br>
  <h1><%= image_tag("mobilewrxlogo.jpg") %></h1>
  <br>
</div>

app/views/welcome/contact.html.erb
<div>
  <center>
    <br>
  <h1><%= image_tag("mobilewrxlogo.jpg") %></h1>
  <br>
</div>

app/views/welcome/faq.html.erb
<div>
  <center>
    <br>
  <h1><%= image_tag("mobilewrxlogo.jpg") %></h1>
  <br>
</div>

app/views/welcome/how.html.erb
<div>
  <center>
    <br>
  <h1><%= image_tag("mobilewrxlogo.jpg") %></h1>
  <br>
</div>

app/views/welcome/index.html.erb
<div class="page-header">
  <center>
    <br>
  <h1><%= image_tag("mobilewrxlogo.jpg") %></h1>
  <h5>MobileWRX is Victoria's premium online marketing tool!</h5>
</center>
</div>
<br>
<div class="row">
  <div class="span3">
    <div class="thumbnail">
    <h2 align="center">Free</h2>
    <p>This is some content about how create point 1 is. You should really use Bloccit because of it! No seriously, it really is amazing and great and you should really check it out.</p>
    <br>
    <br>
    <p align="center"><a href="#" class="btn btn-primary">Try</a></p>
  </div>
</div>
<div class="row">
  <div class="span3">
    <div class="thumbnail">
    <h2 align="center">Bronze</h2>
    <p>This is some content about how create point 1 is. You should really use Bloccit because of it! No seriously, it really is amazing and great and you should really check it out.</p>
    <br />
    <br />
    <p align="center"><a href="#" class="btn btn-primary">Buy</a></p>
  </div>
</div>
  <div class="span3">
    <div class="thumbnail">
    <h2 align="center">Gold</h2>
    <p>This is some content about how create point 2 is. You should really use Bloccit because of it! No seriously, it really is amazing and great and you should really check it out.</p>
    <br>
    <br>
    <p align="center"><a href="#" class="btn btn-primary">Buy</a></p>
  </div>
</div>
  <div class="span3">
    <div class="thumbnail">
    <h2 align="center">Platinum</h2>
    <p>This is some content about how create point 3 is. You should really use Bloccit because of it! No seriously, it really is amazing and great and you should really check it out.</p>
    <br>
    <br>
    <p align="center"><a href="#" class="btn btn-primary">Buy</a></p>
  </div>
</div>

app/views/welcome/promotions.html.erb
<h1>Welcome#promotions</h1>
<p>Find me in app/views/welcome/promotions.html.erb</p>